# Setup
title:        Parallel Closeness Centrality with Application to Facebook Graphs
tagline:      Anton Kuznetsov and Aditya Bhushan
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Anton Kuznetsov
  url:        http://github.com/antonkuz
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
