centrality-omp: centrality-omp.cpp
	g++ -std=c++11 -fopenmp -O3 -g -o centrality-omp centrality-omp.cpp
centrality-boost: centrality-boost.cpp
	g++ -std=c++11 -O3 -g -o centrality-boost centrality-boost.cpp
centrality-omp-fb: centrality-omp-fb.cpp
	g++ -std=c++11 -fopenmp -O3 -g -o centrality-omp-fb centrality-omp-fb.cpp
fw: fw-snap.cpp
	g++ -std=c++11 -fopenmp -O3 -g -o fw fw-snap.cpp
